#pragma once
#include <string>

enum TipoToken {
    ID, ENTERO, DECIMAL, CADENA, MAS, INCREMENTO, MENOS, DECREMENTO,
    MULTIPLICACION, DIVISION, ASIGNACION, IGUALDAD, DESIGUALDAD,
    SIMBOLO, ERROR_LEX, FIN, COMENTARIO_LINEA, COMENTARIO_BLOQUE,

    PAREN_ABRE, PAREN_CIERRA, CORCHETE_ABRE, CORCHETE_CIERRA,
    LLAVE_ABRE, LLAVE_CIERRA, LITERAL_CARACTER,

    KW_ENTERO, KW_CLASE, KW_INTERRUPTOR, KW_CASO, KW_CARACTER, KW_CADENA_TIPO,
    KW_SI, KW_SINO, KW_DEMAS, KW_MIENTRAS, KW_HACER, KW_QUEBRAR,
    KW_VERDADERO, KW_FALSO, KW_BOOL, KW_DOBLE,

    OP_AND, OP_OR, OP_XOR, OP_NOT,
    MENOR_QUE, MAYOR_QUE, MENOR_IGUAL, MAYOR_IGUAL,
    KW_IMPRIMIR, KW_LEER, KW_LIMPIAR_PANTALLA, PUNTO_COMA
};

const std::string NOMBRES_TOKENS[] = {
    "ID", "ENTERO", "DECIMAL", "CADENA", "MAS", "INCREMENTO", "MENOS", "DECREMENTO",
    "MULTIPLICACION", "DIVISION", "ASIGNACION", "IGUALDAD", "DESIGUALDAD",
    "SIMBOLO", "ERROR_LEX", "FIN", "COMENT_LINEA", "COMENT_BLOQUE",
    "PAREN_ABRE", "PAREN_CIERRA", "CORCH_ABRE", "CORCH_CIERRA",
    "LLAVE_ABRE", "LLAVE_CIERRA", "LIT_CHAR",
    "KW_ENTERO", "KW_CLASE", "KW_INTERRUPTOR", "KW_CASO", "KW_CARACTER", "KW_CADENA",
    "KW_SI", "KW_SINO", "KW_DEMAS", "KW_MIENTRAS", "KW_HACER", "KW_QUEBRAR",
    "KW_VERDADERO", "KW_FALSO", "KW_BOOL", "KW_DOBLE",
    "OP_AND", "OP_OR", "OP_XOR", "OP_NOT",
    "MENOR_QUE", "MAYOR_QUE", "MENOR_IGUAL", "MAYOR_IGUAL",
    "KW_IMPRIMIR", "KW_LEER", "KW_LIMPIAR_PANTALLA", "PUNTO_COMA"
};

struct Token {
    TipoToken tipo;
    std::string lexema;
    int linea;
    int columna;
};