#pragma once
#include <string>

enum TipoToken {
    ID, ENTERO, DECIMAL, CADENA, MAS, INCREMENTO, MENOS, DECREMENTO,
    MULTIPLICACION, DIVISION, ASIGNACION, IGUALDAD, DESIGUALDAD,
    SIMBOLO, FUNCION_PROPIA, ERROR_LEX, FIN, COMENTARIO_LINEA, COMENTARIO_BLOQUE,

    PAREN_ABRE, PAREN_CIERRA, CORCHETE_ABRE, CORCHETE_CIERRA,
    LLAVE_ABRE, LLAVE_CIERRA, LITERAL_CARACTER,

    KW_ENTERO, KW_CLASE, KW_INTERRUPTOR, KW_CASO, KW_CARACTER, KW_CADENA_TIPO,
    KW_SI, KW_SINO, KW_DEMAS, KW_MIENTRAS, KW_HACER, KW_QUEBRAR,
    KW_VERDADERO, KW_FALSO, KW_BOOL, KW_DOBLE,

    AND_LOGICO, OR_LOGICO,
    MENOR_QUE, MAYOR_QUE, MENOR_IGUAL, MAYOR_IGUAL
};

const std::string NOMBRES_TOKENS[] = {
    "ID", "ENTERO", "DECIMAL", "CADENA", "MAS", "INCREMENTO", "MENOS", "DECREMENTO",
    "MULTIPLICACION", "DIVISION", "ASIGNACION", "IGUALDAD", "DESIGUALDAD",
    "SIMBOLO", "FUNCION_PROPIA", "ERROR", "FIN", "COMENT_LINEA", "COMENT_BLOQUE",
    "PAREN_ABRE", "PAREN_CIERRA", "CORCH_ABRE", "CORCH_CIERRA",
    "LLAVE_ABRE", "LLAVE_CIERRA", "LIT_CHAR",
    "KW_ENTERO", "KW_CLASE", "KW_INTERRUPTOR", "KW_CASO", "KW_CARACTER", "KW_CADENA",
    "KW_SI", "KW_SINO", "KW_DEMAS", "KW_MIENTRAS", "KW_HACER", "KW_QUEBRAR",
    "KW_VERDADERO", "KW_FALSO", "KW_BOOL", "KW_DOBLE",
    "AND_LOGICO", "OR_LOGICO",
    "MENOR_QUE", "MAYOR_QUE", "MENOR_IGUAL", "MAYOR_IGUAL"
};

struct Token {
    TipoToken tipo;
    std::string lexema;
    int linea;
    int columna;
};